name: receive-dispatch

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        type: string
      workflow_run_id:
        required: true
        type: string

jobs:
  repo_dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Print Message
      run: |
        echo "hi"
