name: receive-dispatch

env:
  ISSUE_CREATION_REPO_NAME: undefined
  ISSUE_TITLE_PREFIX: Workflow Failed

on:
  workflow_dispatch:
    inputs:
      workflow_repo_name:
        required: true
        type: string
      workflow_run_id:
        required: true
        type: string

jobs:
  receive-dispatch:
    runs-on: ubuntu-latest

    steps:
    - name: Get Failed Workflow Details and Logs
      shell: pwsh
      run: |
        Write-Output "Getting workflow logs from repo '${{ inputs.workflow_repo_name }}' and workflow with ID '${{ inputs.workflow_run_id }}'."

        # Get all jobs from workflow run
        $RunDetails = gh run -R https://github.com/${{ inputs.workflow_repo_name }} view ${{ inputs.workflow_run_id }}

        # Regex match failed job IDs
        $FailedJobIds = $RunDetails.ForEach({ [Regex]::Match($PSItem, '^X.+\(ID\s([0-9]+)\)') }).Where({ $PSItem.Success }).Groups.Where({ $PSItem.Name -eq 1 }).Value

        # Get failed job workflow logs
        $FailedJobLogs = $FailedJobIds.ForEach({ gh run -R https://github.com/${{ inputs.workflow_repo_name }} view -j $PSItem --log-failed }) | Sort-Object

        # Remove ANSI color codes from output
        $CleanFailedJobLogs = $FailedJobLogs.ForEach({ $PSItem -replace '\x1b\[[0-9;]*m','' })

        # Build GitHub issue body content
        $IssueBodyContent = @()
        $IssueBodyContent += '### Context'
        $IssueBodyContent += 'Repository: https://github.com/${{ inputs.workflow_repo_name }}'
        $IssueBodyContent += 'Failed Workflow Name: ${{ github.workflow }}'
        $IssueBodyContent += 'Failed Workflow Run: https://github.com/${{ inputs.workflow_repo_name }}/actions/runs/${{ inputs.workflow_run_id }}'
        $IssueBodyContent += ''
        $IssueBodyContent += '### Error'
        $IssueBodyContent += '```txt'
        $IssueBodyContent += $CleanFailedJobLogs
        $IssueBodyContent += '```'
        $IssueBodyContentPath = ".\IssueBodyContent.txt"
        $IssueBodyContent | Out-File -FilePath $IssueBodyContentPath -Force
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_PAT }}

    - name: Create Failed Workflow Issue
      shell: pwsh
      run: |
        $IssueBodyContentPath = (Resolve-Path ".\IssueBodyContent.txt").Path
        gh issue create -R "https://github.com/${{ inputs.workflow_repo_name }}" `
          -t "${{ env.ISSUE_TITLE_PREFIX }} - ${{ inputs.workflow_repo_name }}" `
          -F $IssueBodyContentPath -l bug
      env:
        GH_TOKEN: ${{ github.token }}
