name: start-dispatch

on:
  push:
    branches: [main]

jobs:
  job-1:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Step 1
      run: |
        echo "Attempting to create directory"
        mkdir .\testing
        mkdir .\testing

  job-2:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      shell: pwsh
      run: |
        Write-Output "Attempting to create directory"
        New-Item -Path ./testing -ItemType Directory
        New-Item -Path ./testing -ItemType Directory

  create-issue-on-failure:
    if: ${{ github.event_name == 'push' && failure() }}
    needs: [job-1, job-2]
    runs-on: ubuntu-latest

    steps:
    - name: Call Failed Workflow Issue Creation Workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        token: ${{ secrets.GH_TOKEN_PAT }}
        repo: ${{ github.repository }}
        workflow: receive-dispatch
        inputs: '{"workflow_repo_name":"${{ github.repository }}","workflow_run_id":"${{ github.run_id }}"}'
