name: start-dispatch

on:
  push:
    branches: [main]

jobs:
  job-1:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Step 1
      run: |
        echo "Attempting to create directory"
        mkdir .\testing
        mkdir .\testing

  job-2:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      shell: pwsh
      run: |
        Write-Output "Attempting to create directory"
        New-Item -Path ./testing -ItemType Directory
        New-Item -Path ./testing -ItemType Directory

  create-issue-on-failure:
    if: ${{ github.event_name == 'push' && failure() }}
    needs: [job-1, job-2]
    runs-on: ubuntu-latest

    steps:
    - name: Call Failed Workflow Issue Creation Workflow
      run: |
        curl -X POST -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN_PAT }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.WORKFLOW_NAME }}/dispatches \
          -d '{"ref":"main","inputs":{"workflow_repo_name":"${{ github.repository }}","workflow_run_id":"${{ github.run_id }}"}}'
      env:
        WORKFLOW_NAME: receive-dispatch.yml
